### ISSUE TITLE
Delete custom link on order template

### ISSUE THREAD

**Issue by adornista** [adornista/site#24]
![issue-25](https://cloud.githubusercontent.com/assets/22069481/18339711/ae8629fc-75d3-11e6-8b60-dbf2bac20fd2.png)

**Comment by asapzulu** [comment]
**Time = 10 mins**

I've updated and changed this text to "View Your Design" , try this out.
Still can't figure out the broken link.

**Comment by adornista** [comment]
by the way, the color green should be updated

**Comment by adornista** [comment]
Please update color and delete the link from the template

**Comment by asapzulu** [comment]
"Delete custom link on order template"

> > This will also mean deleting links on all product orders including Ready 2 Wear order emails, please confirm.

**Comment by adornista** [comment]
Well since this link is not working for CREATE DESIGN it looks like you will need to disable for the READY 2 WEAR... at least for now...

**Comment by asapzulu** [comment]
**Time = 60 mins**

Ok this was a bit tough but you missed the checkout thank you screen, see below attachments for this page. There was no indication the user needs to scan the QR codes (I've added that). It had the QR codes broken ( aligned to the right wrong ), it had a product link ( I've disabled it, sorry can't remove it ), the address in the bottom were not aligned ( fixed that ). 

**Before with issues - see below.**
![screen shot 2016-09-30 at 13 10 20](https://cloud.githubusercontent.com/assets/22117203/18981801/f839bc8e-8713-11e6-9a23-e82d112d401e.png)

**Now fixed, see below.**
![screen shot 2016-09-30 at 13 45 53](https://cloud.githubusercontent.com/assets/22117203/18981839/43064534-8714-11e6-9b11-63db80b77210.png)

**Comment by asapzulu** [comment]
You have a new problem. Most email clients block ( links ) + (images ) see my example, most of this is considered spam. You need to enable show images and link. This means some people won't see the QR codes in their emails nor site links. The best bet is to hope they clicked on the QR codes when they checked out otherwise they won't be able to pay you since they can't go back to that page.

See image attached as proof. 

![screen shot 2016-09-30 at 1 46 54 pm](https://cloud.githubusercontent.com/assets/22117203/18981907/bd9ade54-8714-11e6-880e-26c6c852b06c.png)

![screen shot 2016-09-30 at 1 47 12 pm](https://cloud.githubusercontent.com/assets/22117203/18981914/ca3f905a-8714-11e6-946c-f431be7c5c05.png)

**Comment by adornista** [comment]
Ok got it! well perhaps add a message to the email would be a solution "If you are unable to see the QR-Codes for payment in this email, please send us a message at customer@adornista.com."
