### ISSUE TITLE
Behind the brand image bug

### ISSUE THREAD

**Issue by adornista** [adornista/site#44]
![screen shot 2016-09-29 at 20 16 58](https://cloud.githubusercontent.com/assets/22069481/18953757/8a0b2f4a-8682-11e6-93fa-8123798c0524.png)

**Comment by asapzulu** [comment]
Don't put up tickets unless you have 100% proof its a bug. You should do some checking using your logic here. Like...look at the site on another browser ( Chrome / Firefox / Edge ). If the issue is still there, look at it on a PC, look at it on your iPad, look at it on your friends computer. You need to get smart with this, its annoying to see tickets put up. I will use close such tickets or basically ignore. 

![screen shot 2016-09-30 at 2 05 39 pm](https://cloud.githubusercontent.com/assets/22117203/18982242/04e6cfdc-8717-11e6-8a76-965041eb1dc0.png)
