### ISSUE TITLE
[NEW] Create a email address verification

### ISSUE THREAD

**Issue by adornista** [adornista/site#51]
When new customer or recommend a friend is triggered, the user should receive an email for verification of his address. Qualification of email address is important.

**Comment by asapzulu** [comment]
I have been testing something for the past week, it has alot of bugs but I think it can work, there are situations where for example if the user gets two emails in their inbox. This is because of WooCommerce and wordpress default system.

I have added the verification system so now if users register using the official page: https://beta.adornista.com/my-account/ they can verify emails.

If they however are checking out, they can still create an account that one will not get verified without us having the site remember what they last were shopping on by storing cookies. This is because WooCommerce ( this system we are using was not designed to have verifying users and we are tying to bend things which will lead to more problems than actually help ).

**Comment by adornista** [comment]
Add the logo Adornista to the email header which currently says DEMO STORE

![1596278423](https://user-images.githubusercontent.com/22069481/28666097-e3bd9aaa-72bd-11e7-989e-68ee77c69881.jpg)

**Comment by asapzulu** [comment]
The problem with the solution I had implemented and I had worked on it for a week was that the user was getting two emails when they register. 

1- The very newest email is the email with the confirmation link
2 - The old email is a welcome email with their email address asking them to login.
I'm attaching screens below.

**Comment by asapzulu** [comment]
![screen shot 2017-08-04 at 4 21 06 pm](https://user-images.githubusercontent.com/22117203/28960406-1729ca7a-7931-11e7-89c2-a6c7a34ac821.png)
![screen shot 2017-08-04 at 4 20 52 pm](https://user-images.githubusercontent.com/22117203/28960407-172b8658-7931-11e7-9730-bff04846dce9.png)

**Comment by asapzulu** [comment]
The problem with the solution I had implemented and I had worked on it for a week was that the user was getting two emails when they register.

1- The very newest email is the email with the confirmation link
2 - The old email is a welcome email with their email address asking them to login.
I've attached screens below (above).

The problem with this is obviously many people will click the confirm link and may probably have forgotten which email they registered with.

Another problem is they decide not to come back to the site today, they may open the oldest email, go to the site, and be told that they didn't verify their email address.

All this is just confusing to the users, and I tried but couldn't get it to integrate into the custom template.

So the long-term best solution is to buy a proven and tested plugin that can be updated.

I have found this, we can buy its only $18: https://codecanyon.net/item/woocommerce-email-verification/13209934

You can buy it under the Adornista account you have with the other plugins.

**Comment by asapzulu** [comment]
Ok, I have installed and tested this, it works very well.
You can try and create some fake email address on http://yopmail.com   then try and register on the website.

**Comment by asapzulu** [comment]
Time = 1 week  =      5,610 CNY 
Calculated as  ( 60mins x 1.67 /CNY per minute ) x 8hours/day x 7 days 
============

Rate card...
60 mins = 100 CNY ( 1 min = 1.67  CNY )
